---
minio_port: 9000
minio_console_port: 9001
minio_data_dir: /data/minio
minio_user: minio
minio_group: minio
minio_region: eu-central-1
minio_root_user: minioadmin
minio_root_password: minioadmin
minio_listen_address: "0.0.0.0:{{ minio_port }}"
